<a href="https://colab.research.google.com/github/congltk1234/Python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

In [2]:
import numpy as np

#I. **Vector & Matrix:**

1. Sử dụng Numpy để tạo mảng:

In [20]:
'''
np.array(object, dtype = None, copy = True, order = ‘K’, subok = False, ndmin = 0))
Trong đó dtype sẽ tự động xác định kiểu dữ liệu truyền vào
'''
x = np.array([1, 2, 3])
print(x,'\n-----')

y = np.array([1, 2, 3, 'abc'])
print(y,'\n------')

# mảng 2 chiều
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2,'\n------')

[1 2 3] 
-----
['1' '2' '3' 'abc'] 
------
[[1 2 3]
 [4 5 6]] 
------


In [22]:
# mảng 3 chiều
#Hàm np.arange(<start>, <stop>, <step>)
ar3 = np.arange(0,45,3).reshape(3, 5)   
print(ar3)

[[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]]


In [26]:
# tạo mảng 3 chiều gồm 5 phần tử có giá trị 1:
#numpy.ones(shape, dtype=None, order='C')[source]
arr0 = np.ones((3,5))
print(arr0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
#Tạo mảng gồm các phần tử là số 0:

#numpy.zeros(shape, dtype=float, order='C')
a = np.zeros((5,), dtype=int)
print(a)

[0 0 0 0 0]


In [29]:
#tạo mảng 2 chiều gồm 5 phần tử có giá trị value:

#numpy.full(shape, fill_value, dtype=None, order='C')
value = 10
aVal = np.full((2,5), value)
print(aVal)

[[10 10 10 10 10]
 [10 10 10 10 10]]


In [30]:
# tạo ma trận đơn vị kích thước M3:
arrIM = np.eye(3)
print(arrIM)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# tạo mảng 2 chiều có kích thước 2x3 với các phần tử sinh ngẫu nhiên trong khoảng (0,1):
ar = np.random.random((2, 3))
print(ar)

[[0.86855957 0.93575938 0.3523651 ]
 [0.76119815 0.01503162 0.69211849]]


2. Thao tác với mảng:

In [50]:
ar3 = np.arange(0,60,3).reshape(4, 5)   
print(ar3)

[[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]
 [45 48 51 54 57]]


In [44]:
print("Kiểu dữ liệu của phần tử trong mảng:", ar3.dtype)
print("Kích thước của mảng:", ar3.shape)
print("Số phần tử trong mảng:", ar3.size)
print("Số chiều của mảng:", ar3.ndim)

Kiểu dữ liệu của phần tử trong mảng: int64
Kích thước của mảng: (4, 5)
Số phần tử trong mảng: 20
Số chiều của mảng: 2


3. Truy cập phần tử trong mảng

In [61]:
print("ar3[2]=", ar3[2],'\n-----')
print("ar3[1:2]=", ar3[1,2],'\n-----')
print("ar3[0:3]=", ar3[0:3],'\n-----')
print("ar3[:,:1]=", ar3[:,:2],'\n-----')

ar3[2]= [20 21 22 23 24 25 26 27 28 29] 
-----
ar3[1:2]= 12 
-----
ar3[0:3]= [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 
-----
ar3[:,:1]= [[ 0  1]
 [10 11]
 [20 21]] 
-----


#II. **Các phép tính toán với Matrix:**

In [73]:
A = np.array([[1,2,3], [4,5,6],[7,8,9]],int)
B = np.eye(3, dtype=int)
C = np.arange(0,45,3).reshape(3, 5)   

1. Các phép tính cơ bản:

In [69]:
#Tổng Matrix:
sum = A + B
print(C)

[[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]]


In [76]:
#Tích 2 Ma trận:
multi = A @ C
print(multi)

[[ 6  6]
 [15 15]
 [24 24]]


2. Ma trận chuyển vị:

In [79]:
#np.transpose(matrix)
print('Ma trận chuyển vị của A:\n',np.transpose(multi))

Ma trận chuyển vị của A:
 [[ 6 15 24]
 [ 6 15 24]]


3. Ma trận nghịch đảo